language: java
jdk:
- oraclejdk7

before_install:
  - export WORKDIR=$(pwd)
  - wget --no-check-certificate https://github.com/OpenRefine/OpenRefine/archive/2.6-beta.1.tar.gz -O /tmp/OpenRefine.tar.gz
  - tar xzf /tmp/OpenRefine.tar.gz; rm /tmp/OpenRefine.tar.gz; mv OpenRefine-2.6-beta.1 OpenRefine
  - wget https://github.com/fadmaa/grefine-rdf-extension/archive/v0.9.0.tar.gz -O /tmp/v0.9.0.tar.gz
  - tar xzvf /tmp/v0.9.0.tar.gz && rm /tmp/v0.9.0.tar.gz; mv grefine-rdf-extension-0.9.0 OpenRefine/extensions/rdf-extension
  - cd OpenRefine; ant build jar_server jar_webapp
  - cd extensions/rdf-extension; JAVA_TOOL_OPTIONS='-Dfile.encoding=UTF-8' ant build
  - cd $WORKDIR; OPENREFINE_ROOT=$WORKDIR/OpenRefine ./bin/refine-import.sh

install: $WORKDIR/OpenRefine/refine -x refine.headless=true &