language: java
jdk:
- oraclejdk7

before_install:
  - export WORKDIR=$(pwd)
  - git clone --branch 2.6-beta.1 https://github.com/OpenRefine/OpenRefine.git OpenRefine
  - git clone --branch v0.9.0 https://github.com/fadmaa/grefine-rdf-extension.git OpenRefine/extensions/rdf-extension
  - cd OpenRefine; ant build jar_server jar_webapp
  - cd extensions/rdf-extension; JAVA_TOOL_OPTIONS='-Dfile.encoding=UTF-8' ant build
  - cd $WORKDIR; OPENREFINE_ROOT=$WORKDIR/OpenRefine ./bin/refine-import.sh

install: $WORKDIR/OpenRefine/refine -x refine.headless=true &