language: java
sudo: false
jdk:
- oraclejdk7
before_install:
- export WORKDIR=$(pwd)
- git clone --branch 2.6-beta.1 https://github.com/OpenRefine/OpenRefine.git OpenRefine
- git clone --branch v0.9.0 https://github.com/fadmaa/grefine-rdf-extension.git OpenRefine/extensions/rdf-extension
- cd OpenRefine; ant build jar_server jar_webapp
- cd extensions/rdf-extension; JAVA_TOOL_OPTIONS='-Dfile.encoding=UTF-8' ant build
- cd $WORKDIR; OPENREFINE_ROOT=$WORKDIR/OpenRefine ./bin/refine-import.sh
install: "$WORKDIR/OpenRefine/refine -x refine.headless=true &"
deploy:
  provider: releases
  api_key:
    secure: fJY201NThX+mQ2cln67MoPD2hllO2J/xOskX5wGRFAc+unFPM7KGzIPeVdInpTySwjJiNd2MnKhgdLJPcHtfVvvP1RzfrpLX0MpOh/UGg2pWL+XwB6aRKk516pWSj691daZOrCaZc4oMvoptl8N+TaH9qsLb+kqmxetQT7hnfwQ=
  skip_cleanup: true
  file:
    - clients/clients-transformer/target/clients-transformer-$TRAVIS_TAG-jar-with-dependencies.jar
    - clients/clients-cli/target/clients-cli-$TRAVIS_TAG-jar-with-dependencies.jar
  on:
    repo: fusepoolP3/p3-batchrefine
    tags: true
